### ISSUE TITLE
Will you ever make this transactional?

### ISSUE THREAD

**Issue by tarikdevapp** [adamosoftware/Excel2SqlServer.Library#8]

**Comment by adamfoneil** [comment]
what does that mean?

**Comment by tarikdevapp** [comment]
Thank you for replying! Will you consider making the SaveAs (the method which you can find in ExcelLoader) transactional? SqlTransact with Adapter InsertCommande.

**Comment by adamfoneil** [comment]
Okay thanks for clarifying. I wasn't planning on adding transaction support. I see this is as unnecessarily complicated (due to two different code paths -- one for transactions, one without) and potentially long-running. If I'm using transactions, I want to assure that they're very short. A spreadsheet import can be pretty big. If you can help me see the benefit, I'll consider, but you'll need to make the change and submit PR

**Comment by tarikdevapp** [comment]
Thank you so much for the respond! You are correct, it wouldn't be necessarily.
